name: LastSeen
main: com.adognamedspot.lastseen.LastSeen
version: ${project.version}
author: A DoG NaMeD SpoT
api-version: 1.19
commands:
   last:
      description: Displays the last few players to log in.
      usage: /<command>
      permission: <plugin name>.last
      permission-message: You don't have <permission>
   seen:
      description: Displays the last time a player was seen onine.
      usage: /<command> player
      permission: <plugin name>.seen
      permission-message: You don't have <permission>
   info:
      description: Displays in depth info on a player.
      usage: /<command> player
      permission: <plugin name>.info
      permission-message: You don't have <permission>
   stats:
      description: Displays Top server stats.
      usage: /<command>
      permission: <plugin name>.stats   
      permission-message: You don't have <permission>
permissions:
   lastseen.last:
      description: Allows last command
      default: true
   lastseen.seen:
      description: Allows seen command
      default: true
   lastseen.info:
      description: Allows info command
      default: true
   lastseen.admininfo:
      description: Allows info command to lookup other players
      default: false
   lastseen.stats:
      description: Allows stats command
      default: true
   lastseen.*:
      description: Wildcard permission
      default: op
      children:
         lastseen.last: true
         lastseen.seen: true
         lastseen.info: true
         lastseen.admininfo: true
         lastseen.stats: true